# FILE: deploy/helm/templates/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tcd.fullname" . }}
  labels: {{- include "tcd.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels: {{- include "tcd.selectorLabels" . | nindent 6 }}
