# FILE: deploy/helm/templates/servicemonitor.yaml
{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tcd.fullname" . }}
  labels: {{- include "tcd.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "tcd.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
{{- end }}
